### ISSUE TITLE
Recast troubleshooting

### ISSUE THREAD

**Issue by jackpoz** [stoneharry/mmaps-for-custom-maps#1]
Related to https://github.com/stoneharry/mmaps-for-custom-maps?tab=readme-ov-file#recast-debug

>When opening Recast Debug, on the rop right under Sample select Tile Mesh. TrinityCore only supports Tile Mesh.
Under Input Mesh select the .obj for the tile you want to debug.
Ensure TrinityCore Configs is selected.
On the left panel, select Test Navmesh.

You need to reselect the obj in Tile Mesh after enabling TrinityCore settings, otherwise the white hitbox is not 533.33f square as that is calculated only on load (it will use the obj boundaries instead).

That's very useful to notice where tile boundaries are.

**Comment by jackpoz** [comment]
@stoneharry making this show up in your notifications

**Comment by stoneharry** [comment]
https://github.com/stoneharry/mmaps-for-custom-maps/commit/377a079e4fdb65f6b57247ec8e86d99626ccdf92

If you are happy with that, we can close the issue. Thank you
